#!/bin/sh

# Change `style.css` or `style.min.css` to whatever you would like your compiled
# stylesheet to be called. Do not rename `style.scss` or alter references to it.

# No minification
#sass --watch style.scss:style.css --style expanded

cd /
cd /Applications/MAMP/htdocs/

#replace 'framework' with name of project folder being updated
cd jonty/
# -----

cd assets/

sass --sourcemap=none --watch scss/_compiler.scss:css/architecture.min.css --style compressed --precision 9


exit 0
